name: AutomationPro Tests

on:
  schedule:
    - cron: '0 9 * * *' # Daily at 9 AM UTC
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install @playwright/test node-fetch
      - run: npx playwright install
      - run: npx playwright test
      - run: node monitor.js
